address = "${TF_ADDRESS}"
lock_address = "${TF_ADDRESS}/lock"
unlock_address = "${TF_ADDRESS}/lock"
username = "${TF_USERNAME}"
password = "${TF_PASSWORD}"
lock_method = "POST"
unlock_method = "DELETE"
retry_wait_min = "5"