image: registry.gitlab.com/caohoangphuctd/aws-infrastucture/container-docker:latest

# services:
#   - docker:18.09-dind

variables:
  VENV_DIR: ${CI_PROJECT_DIR}/venv

stages:
  - tests

tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR

  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version
