image: registry.gitlab.com/caohoangphuctd/aws-infrastucture/container-docker:latest

variables:
  VENV_DIR: ${CI_PROJECT_DIR}/venv

stages:
  - tests
  - working-plan
before_script:
  - cp /usr/local/src/Makefile $CI_PROJECT_DIR/Makefile
tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR

  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version
    - ls
    - make help

working-plan:
  stage: working-plan
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
  variables:
    TF_BACKEND_CONFIG: environments/backend-dev.hcl
    TF_ROOT: terraform
    # TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
    # TF_USERNAME: gitlab-ci-token
    # TF_PASSWORD: ${CI_JOB_TOKEN}
  script:
    - cd ${TF_ROOT} && terraform init -backend-config="address=https://gitlab.com/api/v4/projects/${CI_PROJECT_DIR}/terraform/state/state" -backend-config="lock_address=https://gitlab.com/api/v4/projects/${CI_PROJECT_DIR}/terraform/state/state/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/${CI_PROJECT_DIR}/terraform/state/state/lock" -backend-config="username=${GITLAB_USER_NAME}" -backend-config="password=s3M9D8BiwmWFgCktCfxU" -backend-config="lock_method=POST" -backend-config="unlock_method=DELETE" -backend-config="retry_wait_min=5"
