image:
  name: hashicorp/terraform:latest

default:
  tags:
    # To support custom gitlab runner
    - gitlab-org
  

stages:
  - tests

tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version
