image: registry.gitlab.com/caohoangphuctd/aws-infrastucture/container-docker:latest

variables:
  VENV_DIR: ${CI_PROJECT_DIR}/venv

stages:
  - tests
  - working-plan

tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR

  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version

working-plan:
  stage: working-plan
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
  variables:
    TERRAFORM_DIR: terraform
  script:
    - cd ${TERRAFORM_DIR} && terraform init && terraform plan