image: registry.gitlab.com/caohoangphuctd/aws-infrastucture/container-docker:latest

variables:
  VENV_DIR: ${CI_PROJECT_DIR}/venv

stages:
  - tests
  - working-plan
before_script:
  - cp /usr/local/src/Makefile $CI_PROJECT_DIR/Makefile
tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR

  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version
    - ls
    - make help

.prepare_dev_configs: &prepare_dev_configs
  - envsubst < $TF_BACKEND_CONF_PATH.tpl > $TF_BACKEND_CONF_PATH

working-plan:
  stage: working-plan
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
  variables:
    TF_BACKEND_CONF_PATH: terraform/gcp/environments/dev/backend-dev.hcl
    TF_BACKEND_CONFIG: environments/backend-dev.hcl
    TF_ROOT: terraform
    
  script:
    - *prepare_dev_configs
    - make tf_init
