image: registry.gitlab.com/caohoangphuctd/aws-infrastucture/container-docker:latest

variables:
  VENV_DIR: ${CI_PROJECT_DIR}/venv
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
  TF_USERNAME: gitlab-ci-token
  TF_PASSWORD: ${CI_JOB_TOKEN}
stages:
  - tests
  - working-plan

tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR

  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version
    - ls

working-plan:
  stage: working-plan
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
  variables:
    TF_BACKEND_CONFIG: environments/backend-dev.hcl
    TF_ROOT: terraform
  script:
    - make --help && terraform plan