image: docker:18.09

services:
  - docker:18.09-dind


default:
  tags:
    # To support custom gitlab runner
    - gitlab-org

variables:
  - VENV_DIR: $CI_PROJECT_DIR/venv

stages:
  - tests

tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}

  script:
    - echo "Hello Cao Hoang Phuc"
    # - terraform --version
