image:
  name: hashicorp/terraform:latest

# default:
#   tags:
#     # To support custom gitlab runner
#     - k8s-deployments
  

stages:
  - tests

tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
  script:
    - echo "Hello Cao Hoang Phuc"
