image: registry.gitlab.com/caohoangphuctd/aws-infrastucture/container-docker:latest

variables:
  VENV_DIR: ${CI_PROJECT_DIR}/venv
  ENV_DIR: ${CI_PROJECT_DIR}/terraform/environments

stages:
  - tests
  - working-apply
  - working-destroy

before_script:
  - cp /usr/local/src/Makefile $CI_PROJECT_DIR/Makefile
tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR

  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version
    - ls
    - make help

.prepare_dev_configs: &prepare_dev_configs
  - envsubst < $TF_BACKEND_CONF_PATH.tpl > $TF_BACKEND_CONF_PATH

working-apply:
  stage: working-apply
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
      - $ENV_DIR
    policy: push
  variables:
    TF_BACKEND_CONF_PATH: terraform/environments/backend-dev.hcl
    TF_BACKEND_CONFIG: environments/backend-dev.hcl
    TF_ROOT: terraform
    TF_VARS_CONFIG: environments/dev.tfvars
  script:
    - *prepare_dev_configs
    - make tf_init
    - make tf_create
working-destroy:
  stage: working-destroy
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
      - $ENV_DIR
    policy: pull
  variables:
    TF_BACKEND_CONF_PATH: terraform/environments/backend-dev.hcl
    TF_BACKEND_CONFIG: environments/backend-dev.hcl
    TF_ROOT: terraform
    TF_VARS_CONFIG: environments/dev.tfvars
  script:
    # - *prepare_dev_configs
    - make tf_init
    - make tf_destroy
