image: registry.gitlab.com/caohoangphuctd/aws-infrastucture/container-docker:latest

variables:
  VENV_DIR: ${CI_PROJECT_DIR}/venv

stages:
  - tests
  - working-plan
before_script:
  - cp /usr/local/src/Makefile $CI_PROJECT_DIR/Makefile
tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR

  script:
    - echo "Hello Cao Hoang Phuc"
    - terraform --version
    - ls
    - make help

working-plan:
  stage: working-plan
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - $VENV_DIR
  variables:
    TF_BACKEND_CONFIG: environments/backend-dev.hcl
    TF_ROOT: terraform
    ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
    USERNAME: gitlab-ci-token
    PASSWORD: ${CI_JOB_TOKEN}
  script:
    - make help && make tf_init