address="https://gitlab.com/api/v4/projects/${CI_PROJECT_DIR}/terraform/state/${CI_COMMIT_REF_SLUG}" 
lock_address="https://gitlab.com/api/v4/projects/${CI_PROJECT_DIR}/terraform/state/${CI_COMMIT_REF_SLUG}/lock" 
unlock_address="https://gitlab.com/api/v4/projects/${CI_PROJECT_DIR}/terraform/state/${CI_COMMIT_REF_SLUG}/lock" 
username="${GITLAB_USER_NAME}" 
password="s3M9D8BiwmWFgCktCfxU" 
lock_method="POST" 
unlock_method="DELETE" 
retry_wait_min="5"