state_address = "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}"
# lock_address = "${ADDRESS}/lock"
# unlock_address = "${ADDRESS}/lock"
# username = "${USERNAME}"
# password = "${PASSWORD}"
# lock_method = "POST"
# unlock_method = "DELETE"
# retry_wait_min = "5"