address = "${ADDRESS}"
lock_address = "${ADDRESS}/lock"
unlock_address = "${ADDRESS}/lock"
username = "${USERNAME}"
password = "${PASSWORD}"
lock_method = "POST"
unlock_method = "DELETE"
retry_wait_min = "5"